allowBuilds:
  '@parcel/watcher': true
  electron: true
  esbuild: true
  node-pty: true

enablePrePostScripts: false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - electron
  - esbuild
  - node-pty
  - playwright

shellEmulator: true

supportedArchitectures:
  os:
    - current
  cpu:
    - current
